# Generated by Django 2.2.24 on 2021-10-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='api_item_Id',
            new_name='listing_id',
        ),
    ]
