# Generated by Django 2.2.24 on 2021-10-05 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211005_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='listing_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='API Link/Identifier'),
        ),
    ]
