# Generated by Django 2.2.24 on 2021-10-05 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211005_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='last_modified',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Epoch time of Last Update to Item'),
        ),
    ]
