# Generated by Django 2.2.24 on 2021-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_cost',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Cost in Points'),
        ),
    ]
