# Generated by Django 2.2.24 on 2021-10-07 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cartitem_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorcatalogitem',
            name='point_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Driver Point Value'),
        ),
    ]
