# Generated by Django 2.2.24 on 2021-10-20 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20211019_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateTime of the Last Update to Item'),
        ),
    ]
