# Generated by Django 2.2.24 on 2021-09-20 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default='driver', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Role Name')),
                ('first_name', models.CharField(default='N/A', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='First Name')),
                ('last_name', models.CharField(default='N/A', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Last Name')),
                ('phone_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999999)], verbose_name='Phone Number')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last User Login')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='If User Verified Email')),
                ('is_active_account', models.BooleanField(default=True, verbose_name='If User Has Account Enabled')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
