# Generated by Django 2.2.24 on 2021-09-20 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='N/A', max_length=60, unique=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='num_of_points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='N/A', max_length=60, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=9, verbose_name='Phone Number'),
        ),
    ]
