# Generated by Django 2.2.24 on 2021-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210920_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account_id',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
