# Generated by Django 2.2.24 on 2021-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210920_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Phone Number'),
        ),
    ]
