# Generated by Django 2.2.24 on 2021-09-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210920_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='email',
        ),
    ]
