# Generated by Django 2.2.24 on 2021-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_activation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='NOT_SET', max_length=25, verbose_name='Password'),
        ),
    ]
