# Generated by Django 2.2.24 on 2021-09-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
