# Generated by Django 2.2.24 on 2021-09-22 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210920_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company Name')),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999999)], verbose_name='Phone Number')),
                ('street_address', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company Street Address')),
                ('city', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company City')),
                ('state', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company State')),
                ('zipcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(99999)], verbose_name='Zip Code')),
                ('point_ratio', models.IntegerField(default=1, verbose_name='US Cents to Catalog Points Ratio')),
                ('about_info', models.CharField(default='Enter about me info here', max_length=1000000, verbose_name='About sponsor')),
            ],
        ),
    ]
