# Generated by Django 2.2.24 on 2021-09-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sponsororganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, default='AvatarDefault.jpg', null=True, upload_to='content/static', verbose_name='profile picture'),
        ),
    ]
