# Generated by Django 2.2.24 on 2021-09-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210924_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, default='IMG/AD.png', null=True, upload_to='IMG/'),
        ),
    ]
