# Generated by Django 2.2.24 on 2021-09-26 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210924_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='viewing_as',
            field=models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default=models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default='driver', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Role Name'), max_length=25, verbose_name='Viewing As'),
        ),
    ]
