# Generated by Django 2.2.24 on 2021-09-27 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_useraccount_type_to_revert_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='type_to_revert_to',
            field=models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default='driver', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Type To Revert To'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='viewing_as',
            field=models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default='driver', max_length=25, verbose_name='Viewing As'),
        ),
    ]
