# Generated by Django 2.2.24 on 2021-09-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210927_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_to', models.CharField(max_length=60, verbose_name='Awarded To')),
                ('awarded_by', models.CharField(max_length=60, verbose_name='Awarded By')),
                ('num_points_awarded', models.IntegerField(verbose_name='Points Awarded')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Awarded')),
            ],
        ),
    ]
