# Generated by Django 2.2.24 on 2021-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_awardpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/AD.png', null=True, upload_to='static/'),
        ),
    ]
