# Generated by Django 2.2.24 on 2021-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210929_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=25, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/profile_pics/AD.png', null=True, upload_to='static/'),
        ),
    ]
