# Generated by Django 2.2.24 on 2021-10-05 13:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211005_0818'),
        ('accounts', '0025_auto_20210929_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('inCart', 'In-Cart'), ('ordered', 'Ordered'), ('shipping', 'Shipping'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('delivered', 'Delivered'), ('returnRequest', 'Return In-Progress'), ('returned', 'Returned')], max_length=25, verbose_name='Order Status')),
                ('last_status_change', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Last DateTime of OrderStatus Update')),
                ('retail_at_order', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Retail Price (MSRP) at Order Time')),
                ('points_at_order', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Driver Point Cost at Order Time')),
                ('ordering_driver', models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=None, to='accounts.SponsorOrganization')),
                ('sponsor_catalog_item', models.ForeignKey(blank=True, null=True, on_delete=None, to='catalog.SponsorCatalogItem')),
            ],
        ),
    ]
