# Generated by Django 2.2.24 on 2021-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211007_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='postal_code',
            field=models.IntegerField(null=True, verbose_name='Postal Code'),
        ),
    ]
