# Generated by Django 2.2.24 on 2021-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211007_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='all_sponsors',
            field=models.ManyToManyField(null=True, related_name='all_sponsors', to='accounts.SponsorOrganization'),
        ),
    ]
