# Generated by Django 2.2.24 on 2021-10-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='all_sponsors',
            field=models.ManyToManyField(related_name='all_sponsors', to='accounts.SponsorOrganization'),
        ),
    ]
