# Generated by Django 2.2.24 on 2021-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_awardpoints_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AwardPoints',
            new_name='AwardPointsModel',
        ),
    ]
