# Generated by Django 2.2.24 on 2021-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20211022_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='points_alerts',
            field=models.BooleanField(default=True, verbose_name='If Points Alerts Are Active'),
        ),
    ]
