# Generated by Django 2.2.24 on 2021-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_useraccount_points_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='order_alerts',
            field=models.BooleanField(default=True, verbose_name='If Order Alerts Are Active'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='order_issue_alerts',
            field=models.BooleanField(default=True, verbose_name='If Order Issue Alerts Are Active'),
        ),
    ]
