# Generated by Django 2.2.24 on 2021-11-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date/TimeAwarded')),
                ('status', models.CharField(max_length=25, verbose_name='Approval Status')),
                ('reason', models.CharField(default='N/A', max_length=250, verbose_name='Reason')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.SponsorOrganization')),
            ],
        ),
    ]
