# Generated by Django 2.2.24 on 2021-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_applicationaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='Username')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date/Time Awarded')),
                ('result', models.CharField(max_length=25, verbose_name='Result')),
            ],
        ),
        migrations.RenameModel(
            old_name='AwardPointsModel',
            new_name='PointsAudit',
        ),
    ]
